spring.application.name=financial-reconciliation

spring.datasource.url=jdbc:postgresql://localhost:5432/batch-db
spring.datasource.username=batch-user
spring.datasource.password=b41chP4ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=false

spring.batch.jdbc.initialize-schema=always

spring.batch.job.enabled=false